APPLY_FIXES: all

DISABLE_LINTERS:
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - TYPESCRIPT_STANDARD
  - JSON_JSONLINT
  - YAML_YAMLLINT
  - REPOSITORY_TRIVY

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false